Update A1 to A93 mission "memo" information
antest1/kcanotify-gamedata pull request #3
Opened 2022-11-29 11:26 UTC by skysumbra

Update A1 to A93 mission "memo" information

2022-12-06 02:17 UTC, skysumbra commented
Commit 3rd  version add factory and drill mission description.

2022-12-06 13:01 UTC, antest1 requested changes
Hi skysumbra! first of all, thanks for your great contributions! 🙏🙏
I marked lines that need to be fixed before merge, so please check and make new commit!

2022-12-07 06:42 UTC, skysumbra commented on files/quests-tcn.json
> +		"memo" "開發資材*2，高速修復材*2 "
Sorry, i update file again.

2022-12-07 06:49 UTC, skysumbra commented on files/quests-tcn.json
> +		"memo" "開發資材*4 和 改修資材*4"
Update new file, thanks antest1

2022-12-07 06:52 UTC, antest1 commented on files/quests-tcn.json
> +		"memo" "開發資材*4 和 改修資材*4"
oh seems you forgot to update this part, can you check it again?

2022-12-07 08:04 UTC, skysumbra commented on files/quests-tcn.json
> +		"memo" "開發資材*4 和 改修資材*4"
sorry, let me upload again.

2022-12-07 08:17 UTC, skysumbra commented
some "memo" column colon lost in [5ab8bba](https://github.com/antest1/kcanotify-gamedata/pull/3/commits/5ab8bbad3de81616c3af931529878597abd422fa) add

2022-12-07 14:47 UTC, antest1 approved these changes

2022-12-07 14:47 UTC, merged